---
apiVersion: v1
offerings:
  - name: cps
    kind: solution
    catalog_id: eea608f2-fd4a-47cd-9dae-c72653c2bae5
    variations:
      - name: cps
        mark_ready: false
        install_type: extension
        import_only: true
